### ISSUE TITLE
Availability for South Australian Sentinel 2A

### ISSUE THREAD

**Issue by RichardScottOZ** [cirrus-geo/cirrus-earth-search#10]
When I did this, there seemed to only be data from around September 2020?

https://github.com/RichardScottOZ/dask-era5/blob/main/notebook/PANGEO-Sentinel-Intake-SA-OZLocation.ipynb

e.g.

bbox = [129.0000000000000000,-39.0000000000000000, 141.0000000000000000,-26.0000000000000000]
bbox = [138.54207373854032 - 0.01, -34.934374426311145 - 0.01, 138.54207373854032 + 0.01, -34.934374426311145 + 0.01]
#bbox = [138.54207373854032 - 0.5, -34.934374426311145 - 0.5, 138.54207373854032 + 0.5, -34.934374426311145 + 0.5]

dates = '2017-01-01/2020-12-31'

URL='https://earth-search.aws.element84.com/v0'
results = satsearch.Search.search(url=URL,
                                  collections=['sentinel-s2-l2a-cogs'], # note collection='sentinel-s2-l2a-cogs' doesn't work
                                  datetime=dates,
                                  bbox=bbox,   
                                  #property=["eo:cloud_cover<1"],
                                  #query={'eo:cloud_cover': {'lt': 1}},
                                  query={'eo:cloud_cover': {'eq': 0}, 'platform':{'eq': 'sentinel-2a'}},
                                  sort=['<datetime'])

**Comment by TaiWilkin** [comment]
It looks like you've set your search to limit it to only images with no cloud cover. These images are very rare. We suggest setting your cloud cover limit to a larger number in order to return more images.

**Comment by RichardScottOZ** [comment]
At the time that wasn't all I tried though. The other point being that 'middle of the Australian desert' - not so cloudy as some.  Other changes may have fixed this, will check.
