### ISSUE TITLE
Missing Brazil scene

### ISSUE THREAD

**Issue by RichardScottOZ** [cirrus-geo/cirrus-earth-search#12]
I started looking at another area with stackstac, and investigating

got a 404 from rasterio on this one

 File "/home/ubuntu/anaconda3/envs/richard/lib/python3.8/site-packages/stackstac/rio_reader.py", line 334, in _open
    raise RuntimeError(f"retrieval {self.url!r} problem" )
RuntimeError: retrieval 'https://sentinel-cogs.s3.us-west-2.amazonaws.com/sentinel-s2-l2a-cogs/22M/DU2020/8/S2A_22MDU_20200816_0_L2A/B02.tif' problem

The same thing happened for band 3, so I presume this one is missing?

**Comment by RichardScottOZ** [comment]
Another couple

S2A_22MGT_20170610_0_L2A
S2A_22MET_20200816_0_L2A

**Comment by RichardScottOZ** [comment]
S2A_22MES_20200816_0_L2A
S2A_22MDB_20200816_0_L2A

**Comment by RichardScottOZ** [comment]
S2A_22MFB_20200816_0_L2A

**Comment by RichardScottOZ** [comment]
S2A_22MEB_20200816_0_L2A

Seeming like a consistent batch of 08016 missing in this bit of Brazil?

**Comment by RichardScottOZ** [comment]
S2A_22MFA_20200816_0_L2A

**Comment by RichardScottOZ** [comment]
S2A_22MCB_20200816_0_L2A

**Comment by RichardScottOZ** [comment]
S2A_22MEA_20200816_0_L2A

**Comment by RichardScottOZ** [comment]
couple more

S2A_22MEV_20200816_0_L2A
S2A_22MCV_20200816_0_L2A

**Comment by RichardScottOZ** [comment]
Some more

S2A_22MBU_20200816_0_L2A
S2A_22MCU_20200816_0_L2A
S2A_22MDU_20200816_0_L2A
S2A_22MEU_20200816_0_L2A
S2A_22MCT_20200816_0_L2A
S2A_22MET_20200816_0_L2A
S2A_22MBS_20200816_0_L2A
S2A_22MCT_20200816_0_L2A
S2A_22MCS_20200816_0_L2A
S2A_22MBS_20200816_0_L2A
S2A_22MDS_20200816_0_L2A
S2A_22MET_20200816_0_L2A

So maybe 22Ms on 0816

**Comment by RichardScottOZ** [comment]
S2B_23MRP_20200809_0_L2A
S2B_23NLA_20200729_0_L2A
S2A_23MRT_20200807_0_L2A
S2B_23MRM_20200809_0_L2A
S2A_21LZL_20200816_0_L2A
S2A_23NLA_20200803_0_L2A
S2B_23MRN_20200809_0_L2A
S2A_22LBR_20200816_0_L2A
S2B_23MRP_20200730_0_L2A
S2B_23NKA_20200729_0_L2A
S2B_23MRM_20200730_0_L2A
S2A_23MRR_20200804_0_L2A
S2A_21LZK_20200816_0_L2A
S2A_23MRQ_20200804_0_L2A
S2A_23MRS_20200728_0_L2A
S2A_21MZM_20200816_0_L2A
S2A_23MRU_20200807_0_L2A
S2A_23MRS_20200807_0_L2A
S2B_23NLA_20200808_0_L2A
S2B_23MRN_20200730_0_L2A

**Comment by TaiWilkin** [comment]
This has been resolved in [the v1 api](https://earth-search.aws.element84.com/v1).
