### ISSUE TITLE
Missing assets

### ISSUE THREAD

**Issue by carioca-au** [cirrus-geo/cirrus-earth-search#18]
Good Afternoon,

We're doing an update of our metadata, and part of that is checking if files exist.
We've found a few scenes that are missing assets as per the below list:

```
sentinel-s2-l2a-cogs/33/P/TQ/2018/9/S2B_33PTQ_20180909_0_L2A/B01.tif
sentinel-s2-l2a-cogs/39/P/VL/2018/12/S2B_39PVL_20181223_0_L2A/L2A_PVI.tif
sentinel-s2-l2a-cogs/32/L/RP/2018/11/S2A_32LRP_20181127_0_L2A/L2A_PVI.tif
sentinel-s2-l2a-cogs/37/L/DD/2018/11/S2A_37LDD_20181104_0_L2A/L2A_PVI.tif
sentinel-s2-l2a-cogs/28/Q/BM/2018/2/S2A_28QBM_20180205_0_L2A/L2A_PVI.tif
sentinel-s2-l2a-cogs/35/M/NM/2018/9/S2B_35MNM_20180905_0_L2A/L2A_PVI.tif
```

We are about to do a big check for the whole African continent, which may or may not show us new similar situations. If found any new issue, I'll be promptly reporting here.

Thank you for your attention to this matter.

**Comment by TaiWilkin** [comment]
Can you confirm if this is still an issue for you in v1? In v1, `sentinel-s2-l2a-cogs` has been renamed to `sentinel-2-l2a`.

**Comment by fungjj92** [comment]
I checked these bands and indexes in v1. Here's the first one in v1 for reference: https://earth-search.aws.element84.com/v1/collections/sentinel-2-l2a/items/S2B_39PVL_20181223_0_L2A

The above B01 is listed as a jp2, this is undesirable. This is not the only instance so we're scheduled to have to look more broadly.
All the PVI bands above are absent for those scenes. Will likewise have a larger audit of our sentinel2 data in v1.

**Comment by fungjj92** [comment]
This work is captured in our JIRA
