### ISSUE TITLE
Malformed TIFF file paths + missing granules

### ISSUE THREAD

**Issue by piyushrpt** [cirrus-geo/cirrus-earth-search#19]
A number of granules in July / Aug 2020 appear to be missing even though they contain valid STAC entries. The paths for TIFF files in these entries also appear to be malformed.

Examples:
1. https://earth-search.aws.element84.com/v0/collections/sentinel-s2-l2a-cogs/items/S2A_13SCA_20200801_0_L2A
```
aws s3 ls s3://sentinel-cogs/sentinel-s2-l2a-cogs/13/S/CA/2020/8/ --no-sign-request
                           PRE S2A_13SCA_20200821_0_L2A/
                           PRE S2A_13SCA_20200824_0_L2A/
                           PRE S2A_13SCA_20200831_0_L2A/
                           PRE S2B_13SCA_20200819_0_L2A/
                           PRE S2B_13SCA_20200826_0_L2A/
                           PRE S2B_13SCA_20200829_0_L2A/
```

2. https://earth-search.aws.element84.com/v0/collections/sentinel-s2-l2a-cogs/items/S2A_13TCG_20200728_0_L2A
```
aws s3 ls s3://sentinel-cogs/sentinel-s2-l2a-cogs/13/T/CG/2020/7/ --no-sign-request
                           PRE S2A_13TCG_20200705_0_L2A/
                           PRE S2A_13TCG_20200708_0_L2A/
                           PRE S2A_13TCG_20200715_0_L2A/
                           PRE S2A_13TCG_20200718_0_L2A/
                           PRE S2A_13TCG_20200725_0_L2A/
                           PRE S2B_13TCG_20200703_0_L2A/
                           PRE S2B_13TCG_20200710_0_L2A/
                           PRE S2B_13TCG_20200713_0_L2A/
                           PRE S2B_13TCG_20200720_0_L2A/
                           PRE S2B_13TCG_20200723_0_L2A/
```

**Comment by JonDHo** [comment]
This problem still seems to exist. I have found some bad S3 paths in July/August 2020 close to Santiago, Chile. 

For example, https://earth-search.aws.element84.com/v0/collections/sentinel-s2-l2a-cogs/items/S2A_19HDD_20200808_0_L2A contains URLs like
https://sentinel-cogs.s3.us-west-2.amazonaws.com/sentinel-s2-l2a-cogs/19H/DD2020/8/S2A_19HDD_20200808_0_L2A/B01.tif

This is poorly formed in the middle:
 /19H/DD2020/ should of course be /19/H/DD/2020/

but also the key S2A_19HDD_20200808_0_L2A does not exist if you do go to the correct end point.

Other incorrect scenes include (all malformed):
sentinel-cogs/sentinel-s2-l2a-cogs/19H/DD2020/8/S2A_19HDD_20200808_0_L2A/
sentinel-cogs/sentinel-s2-l2a-cogs/19H/DD2020/8/S2A_19HDD_20200808_0_L2A/
sentinel-cogs/sentinel-s2-l2a-cogs/19H/CD2020/8/S2A_19HCD_20200808_0_L2A/
sentinel-cogs/sentinel-s2-l2a-cogs/19H/DC2020/8/S2A_19HDC_20200808_0_L2A/
sentinel-cogs/sentinel-s2-l2a-cogs/19H/CC2020/8/S2A_19HCC_20200808_0_L2A/
sentinel-cogs/sentinel-s2-l2a-cogs/19H/DD2020/8/S2A_19HDD_20200808_0_L2A/
sentinel-cogs/sentinel-s2-l2a-cogs/19H/CD2020/8/S2A_19HCD_20200808_0_L2A/
sentinel-cogs/sentinel-s2-l2a-cogs/19H/DC2020/8/S2A_19HDC_20200808_0_L2A/
sentinel-cogs/sentinel-s2-l2a-cogs/19H/CC2020/8/S2A_19HCC_20200808_0_L2A/
sentinel-cogs/sentinel-s2-l2a-cogs/19H/DD2020/8/S2A_19HDD_20200801_0_L2A/
sentinel-cogs/sentinel-s2-l2a-cogs/19H/CD2020/8/S2A_19HCD_20200801_0_L2A/
sentinel-cogs/sentinel-s2-l2a-cogs/19H/DC2020/8/S2A_19HDC_20200801_0_L2A/
sentinel-cogs/sentinel-s2-l2a-cogs/19H/CC2020/8/S2A_19HCC_20200801_0_L2A/
sentinel-cogs/sentinel-s2-l2a-cogs/19H/DD2020/8/S2A_19HDD_20200801_0_L2A/
sentinel-cogs/sentinel-s2-l2a-cogs/19H/CD2020/8/S2A_19HCD_20200801_0_L2A/
sentinel-cogs/sentinel-s2-l2a-cogs/19H/DC2020/8/S2A_19HDC_20200801_0_L2A/
sentinel-cogs/sentinel-s2-l2a-cogs/19H/CC2020/8/S2A_19HCC_20200801_0_L2A/
sentinel-cogs/sentinel-s2-l2a-cogs/19H/DD2020/7/S2A_19HDD_20200729_0_L2A/
sentinel-cogs/sentinel-s2-l2a-cogs/19H/CD2020/7/S2A_19HCD_20200729_0_L2A/
sentinel-cogs/sentinel-s2-l2a-cogs/19H/DC2020/7/S2A_19HDC_20200729_0_L2A/
sentinel-cogs/sentinel-s2-l2a-cogs/19H/CC2020/7/S2A_19HCC_20200729_0_L2A/
sentinel-cogs/sentinel-s2-l2a-cogs/19H/DD2020/7/S2A_19HDD_20200729_0_L2A/
sentinel-cogs/sentinel-s2-l2a-cogs/19H/CD2020/7/S2A_19HCD_20200729_0_L2A/
sentinel-cogs/sentinel-s2-l2a-cogs/19H/DC2020/7/S2A_19HDC_20200729_0_L2A/
sentinel-cogs/sentinel-s2-l2a-cogs/19H/CC2020/7/S2A_19HCC_20200729_0_L2A/
sentinel-cogs/sentinel-s2-l2a-cogs/19H/DD2020/8/S2B_19HDD_20200813_0_L2A/
sentinel-cogs/sentinel-s2-l2a-cogs/19H/CD2020/8/S2B_19HCD_20200813_0_L2A/
sentinel-cogs/sentinel-s2-l2a-cogs/19H/CC2020/8/S2B_19HCC_20200813_0_L2A/
sentinel-cogs/sentinel-s2-l2a-cogs/19H/DD2020/8/S2B_19HDD_20200813_0_L2A/
sentinel-cogs/sentinel-s2-l2a-cogs/19H/CD2020/8/S2B_19HCD_20200813_0_L2A/
sentinel-cogs/sentinel-s2-l2a-cogs/19H/CC2020/8/S2B_19HCC_20200813_0_L2A/
sentinel-cogs/sentinel-s2-l2a-cogs/19H/DD2020/8/S2B_19HDD_20200803_0_L2A/
sentinel-cogs/sentinel-s2-l2a-cogs/19H/CD2020/8/S2B_19HCD_20200803_0_L2A/
sentinel-cogs/sentinel-s2-l2a-cogs/19H/DC2020/8/S2B_19HDC_20200803_0_L2A/
sentinel-cogs/sentinel-s2-l2a-cogs/19H/CC2020/8/S2B_19HCC_20200803_0_L2A/
sentinel-cogs/sentinel-s2-l2a-cogs/19H/DD2020/8/S2B_19HDD_20200803_0_L2A/
sentinel-cogs/sentinel-s2-l2a-cogs/19H/CD2020/8/S2B_19HCD_20200803_0_L2A/
sentinel-cogs/sentinel-s2-l2a-cogs/19H/DC2020/8/S2B_19HDC_20200803_0_L2A/
sentinel-cogs/sentinel-s2-l2a-cogs/19H/CC2020/8/S2B_19HCC_20200803_0_L2A/
sentinel-cogs/sentinel-s2-l2a-cogs/19H/DD2020/8/S2B_19HDD_20200806_0_L2A/
sentinel-cogs/sentinel-s2-l2a-cogs/19H/CD2020/8/S2B_19HCD_20200806_0_L2A/
sentinel-cogs/sentinel-s2-l2a-cogs/19H/DC2020/8/S2B_19HDC_20200806_0_L2A/
sentinel-cogs/sentinel-s2-l2a-cogs/19H/CC2020/8/S2B_19HCC_20200806_0_L2A/
sentinel-cogs/sentinel-s2-l2a-cogs/19H/DD2020/8/S2B_19HDD_20200806_0_L2A/
sentinel-cogs/sentinel-s2-l2a-cogs/19H/CD2020/8/S2B_19HCD_20200806_0_L2A/
sentinel-cogs/sentinel-s2-l2a-cogs/19H/DC2020/8/S2B_19HDC_20200806_0_L2A/
sentinel-cogs/sentinel-s2-l2a-cogs/19H/CC2020/8/S2B_19HCC_20200806_0_L2A/
sentinel-cogs/sentinel-s2-l2a-cogs/19H/DD2020/8/S2B_19HDD_20200816_0_L2A/
sentinel-cogs/sentinel-s2-l2a-cogs/19H/CD2020/8/S2B_19HCD_20200816_0_L2A/
sentinel-cogs/sentinel-s2-l2a-cogs/19H/DD2020/8/S2B_19HDD_20200816_0_L2A/
sentinel-cogs/sentinel-s2-l2a-cogs/19H/CD2020/8/S2B_19HCD_20200816_0_L2A/
sentinel-cogs/sentinel-s2-l2a-cogs/19H/CC2020/8/S2B_19HCC_20200816_0_L2A/
sentinel-cogs/sentinel-s2-l2a-cogs/19H/CC2020/8/S2B_19HCC_20200816_0_L2A/
sentinel-cogs/sentinel-s2-l2a-cogs/19H/DD2020/8/S2A_19HDD_20200811_0_L2A/
sentinel-cogs/sentinel-s2-l2a-cogs/19H/DD2020/8/S2A_19HDD_20200811_0_L2A/
sentinel-cogs/sentinel-s2-l2a-cogs/19H/CD2020/8/S2A_19HCD_20200811_0_L2A/
sentinel-cogs/sentinel-s2-l2a-cogs/19H/CD2020/8/S2A_19HCD_20200811_0_L2A/
sentinel-cogs/sentinel-s2-l2a-cogs/19H/DC2020/8/S2A_19HDC_20200811_0_L2A/
sentinel-cogs/sentinel-s2-l2a-cogs/19H/DC2020/8/S2A_19HDC_20200811_0_L2A/
sentinel-cogs/sentinel-s2-l2a-cogs/19H/CC2020/8/S2A_19HCC_20200811_0_L2A/
sentinel-cogs/sentinel-s2-l2a-cogs/19H/DC2020/8/S2A_19HDC_20200811_1_L2A/
sentinel-cogs/sentinel-s2-l2a-cogs/19H/CC2020/8/S2A_19HCC_20200811_0_L2A/
sentinel-cogs/sentinel-s2-l2a-cogs/19H/CC2020/8/S2A_19HCC_20200811_1_L2A/
sentinel-cogs/sentinel-s2-l2a-cogs/19H/DC2020/8/S2A_19HDC_20200811_1_L2A/
sentinel-cogs/sentinel-s2-l2a-cogs/19H/CC2020/8/S2A_19HCC_20200811_1_L2A/

**Comment by fungjj92** [comment]
This work is captured in our JIRA

**Comment by JonDHo** [comment]
Is the Jira public? It would be usefully to know what the outcome is or whether it is being fixed.

**Comment by piyushrpt** [comment]
A summary here would again be useful. I noticed that granules near the dateline that were fixed can be queried using the updated field. If that field will be correctly set on each update, we can rely on it to track this

**Comment by fungjj92** [comment]
Thanks for your interest in earthsearch, we're glad to see it being used. Promoting user reported issues into JIRA makes for streamlined housekeeping and puts them in the pipeline to get worked on. The JIRA is private -- but we link to these original GH issues and plan to circle back when there's an update. Thanks all!
