### ISSUE TITLE
Missing assets 2

### ISSUE THREAD

**Issue by carioca-au** [cirrus-geo/cirrus-earth-search#20]
Good Morning,

We're doing a second round of updates on our metadata, and part of that is checking if files exist.
We've found a few scenes that there are missing assets from your bucket, as per the below list:

```
'sentinel-s2-l2a-cogs/37/L/DD/2018/11/S2A_37LDD_20181104_0_L2A/L2A_PVI.tif', 
'sentinel-s2-l2a-cogs/33/P/WM/2018/1/S2A_33PWM_20180124_0_L2A/L2A_PVI.tif', 
'sentinel-s2-l2a-cogs/34/N/HM/2018/9/S2A_34NHM_20180919_0_L2A/L2A_PVI.tif', 
'sentinel-s2-l2a-cogs/34/S/CA/2018/11/S2B_34SCA_20181115_0_L2A/L2A_PVI.tif', 
'sentinel-s2-l2a-cogs/32/L/RP/2018/11/S2A_32LRP_20181127_0_L2A/L2A_PVI.tif', 
'sentinel-s2-l2a-cogs/39/P/UK/2018/12/S2B_39PUK_20181223_0_L2A/L2A_PVI.tif', 
'sentinel-s2-l2a-cogs/34/S/GA/2018/6/S2A_34SGA_20180620_0_L2A/L2A_PVI.tif', 
'sentinel-s2-l2a-cogs/28/Q/BM/2018/2/S2A_28QBM_20180205_0_L2A/L2A_PVI.tif', 
'sentinel-s2-l2a-cogs/36/N/TH/2018/8/S2A_36NTH_20180801_0_L2A/L2A_PVI.tif', 
'sentinel-s2-l2a-cogs/30/S/WD/2018/10/S2B_30SWD_20181013_0_L2A/L2A_PVI.tif', 
'sentinel-s2-l2a-cogs/35/M/NM/2018/9/S2B_35MNM_20180905_0_L2A/L2A_PVI.tif', 
'sentinel-s2-l2a-cogs/36/P/ZB/2018/11/S2A_36PZB_20181126_0_L2A/L2A_PVI.tif', 
'sentinel-s2-l2a-cogs/35/R/KL/2018/11/S2B_35RKL_20181116_0_L2A/L2A_PVI.tif', 
'sentinel-s2-l2a-cogs/35/L/KC/2018/12/S2B_35LKC_20181227_1_L2A/L2A_PVI.tif', 
'sentinel-s2-l2a-cogs/39/P/VL/2018/12/S2B_39PVL_20181223_0_L2A/L2A_PVI.tif', 
'sentinel-s2-l2a-cogs/33/P/TQ/2018/9/S2B_33PTQ_20180909_0_L2A/B01.tif', 
'sentinel-s2-l2a-cogs/35/R/LH/2018/7/S2A_35RLH_20180724_0_L2A/L2A_PVI.tif', 
'sentinel-s2-l2a-cogs/39/P/TN/2018/10/S2A_39PTN_20181012_0_L2A/L2A_PVI.tif', 
'sentinel-s2-l2a-cogs/29/S/PR/2018/11/S2B_29SPR_20181118_0_L2A/L2A_PVI.tif', 
'sentinel-s2-l2a-cogs/35/M/KS/2018/10/S2A_35MKS_20181016_0_L2A/L2A_PVI.tif', 
'sentinel-s2-l2a-cogs/34/P/DQ/2018/7/S2B_34PDQ_20180722_0_L2A/L2A_PVI.tif', 
'sentinel-s2-l2a-cogs/35/K/KT/2018/5/S2A_35KKT_20180523_0_L2A/L2A_PVI.tif', 
'sentinel-s2-l2a-cogs/31/P/BS/2018/1/S2A_31PBS_20180112_0_L2A/L2A_PVI.tif', 
'sentinel-s2-l2a-cogs/39/N/UE/2018/7/S2B_39NUE_20180726_0_L2A/L2A_PVI.tif'
```

This time we have done a big check over 2174227 scenes or the whole African continent. As promised last time, I am listing the missing ones.

Thank you for your attention to this matter.

**Comment by matthewhanson** [comment]
@alexgleith It's not necessarily expected, but appears as though the PVI files don't exist for these scenes.  I'll see if I can find out why

**Comment by alexgleith** [comment]
That one that's missing B01 is a bit of an issue, though! Can you re-process that?

**Comment by carioca-au** [comment]
Hey, @matthewhanson is there any update about the missing B01?

**Comment by matthewhanson** [comment]
@carioca-au @alexgleith sorry, been a bit busy this week, I'll have some time Friday afternoon or early next week and will try to reprocess that scene, and will also take a closer look at the othes.

**Comment by TaiWilkin** [comment]
Can you confirm if this is still an issue for you in v1? In v1, `sentinel-s2-l2a-cogs` has been renamed to `sentinel-2-l2a`.

**Comment by alexgleith** [comment]
Had a quick look at the scene that's missing the band one file and it's missing a whole lot of stuff.

`aws s3 ls s3://sentinel-cogs/sentinel-s2-l2a-cogs/33/P/TQ/2018/9/S2B_33PTQ_20180909_0_L2A/`

> 2020-10-02 17:55:16   62278420 B11.tif
> 2020-10-02 17:55:36   62480861 B12.tif
> 2020-10-02 17:54:49   62197818 B8A.tif
> 2020-10-02 17:47:25     425440 L2A_PVI.tif
> 2022-11-08 15:48:34      16239 S2B_33PTQ_20180909_0_L2A.json
> 2020-10-02 17:57:37    5269371 SCL.tif
> 2020-10-02 17:48:42  332933101 TCI.tif
> 2020-10-02 17:57:22   89962411 WVP.tif
> 2022-11-08 15:48:33     553096 granule_metadata.xml
> 2022-11-08 15:48:33     144943 thumbnail.jpg
> 2022-11-08 15:48:33       1488 tileinfo_metadata.json

Also, the item has links to `jp2` files, which doesn't seem right: https://earth-search.aws.element84.com/v1/collections/sentinel-2-l2a/items/S2B_33PTQ_20180909_0_L2A

**Comment by philvarner** [comment]
It looks like the jp2 asset is used for the default named band assets (e.g., red, blue) if the COG doesn't exist. I don't think that's a great behavior, because then you have the same asset names having different data formats among different Items, and that's not user-friendly when you're expecting a cog. It's also contrary to the `item-assets` definitions advertised in the Collection. We'll likely change that soon.

I'll also look into taking into account when only some of the cogs exist, and make sure they're created before creating the item.  Thanks!

**Comment by fungjj92** [comment]
This work has been moved into JIRA and for good housekeeping we'll close this issue.

**Comment by fungjj92** [comment]
You got it, that is the plan! We have linked to these original GH issues within JIRA. It is more streamlined housekeeping than tracking open issues in two places.
