### ISSUE TITLE
Handle BOA_ADD_OFFSET

### ISSUE THREAD

**Issue by petescarth** [cirrus-geo/cirrus-earth-search#21]
As noted in [Copernicus Sentinel-2: Major Products Upgrade Upcoming](https://sentinels.copernicus.eu/web/sentinel/-/copernicus-sentinel-2-major-products-upgrade-upcoming ) the dynamic range of the L2A data will be shifted by a band-dependent constant called BOA_ADD_OFFSET given in the XML metadata file, and these may vary per-scene-and-date.

After the change the L2A Bottom of Atmosphere (BOA) reflectance (L2A_BOA) will need to be retrieved from the output radiometry using:
`L2A_BOAi = (L2A_DNi + BOA_ADD_OFFSETi) / QUANTIFICATION_VALUEi`

Links to https://github.com/cirrus-geo/cirrus-earth-search/issues/8 as the metadata will now be critical for use of the data.

**Comment by matthewhanson** [comment]
New scenes being generated now have the BOA_ADD_OFFSET applied, and a new Item property `sentinel:boa_offset_applied` has been added, set to `True` for all new scenes with the offset.

Also note that just before Jan 25th when the baseline was updated to 04.00, we also added an Item property `sentinel:processing_baseline` to indicate the version so we can tell which scenes will need to be reprocessed to apply the offset.

I'm keeping this issue open until the updates have been to the scenes since Jan 25th that need to be reprocessed.

**Comment by aleny91** [comment]
Just a clarification: in some cases, the Item property ` sentinel:processing_baseline` is present, but not `sentinel:boa_offset_applied`. 
Here is an example: https://earth-search.aws.element84.com/v0/collections/sentinel-s2-l2a-cogs/items/S2A_32TQM_20220204_0_L2A 

In situations like the one I've just reported, is the offset applied or not?

Many thanks in advance for the support.

**Comment by fschlenz** [comment]
Dear @aleny91, this is also linked to https://github.com/cirrus-geo/cirrus-earth-search/issues/26.

**Comment by fungjj92** [comment]
v0 is no longer supported, v1 data has the `boa_offset_applied` flag, see: https://earth-search.aws.element84.com/v1/collections/sentinel-2-l2a/items/S2A_32TQM_20220204_0_L2A . We would have expected to apply the offset to all v1 Sentinel 2 data where the `processing_baseline=4.00`, but the `boa_offset_applied` flag is false in that link above and for a fair amount of the metadata. We will look into it.

**Comment by fungjj92** [comment]
This work is captured in our JIRA. Closing for good housekeeping.

**Comment by gc-sommer** [comment]
> v0 is no longer supported, v1 data has the `boa_offset_applied` flag, see: https://earth-search.aws.element84.com/v1/collections/sentinel-2-l2a/items/S2A_32TQM_20220204_0_L2A . We would have expected to apply the offset to all v1 Sentinel 2 data where the `processing_baseline=4.00`, but the `boa_offset_applied` flag is false in that link above and for a fair amount of the metadata. We will look into it.

Hi @fungjj92 !

Could you please explain what "v0 is no longer supported" acually means? 
- is there a end of lifetime for the currently running service? Maybe I missed an announcement?
- is still data being updated in the STAC for v0 as new S2 scenes are ingested into the AWS Bucket?
- maybe this "just" means, that the STAC v0 is no longer technically updated anymore but still has current S2 data?

Best regards,
Johannes
