### ISSUE TITLE
Missing scenes in sentinel-cogs

### ISSUE THREAD

**Issue by NikitaGandhi** [cirrus-geo/cirrus-earth-search#22]
We have detected the following assets are missing in sentinel-cogs bucket for 2018 first 6Months:

```
Missing all the scenes:
sentinel-cogs/sentinel-s2-l2a-cogs/31/P/BS/2018/1/S2A_31PBS_20180112_0_L2A/

Missing B02 band:
sentinel-cogs/sentinel-s2-l2a-cogs/33/P/WM/2018/1/S2A_33PWM_20180124_0_L2A/B02.tif
sentinel-cogs/sentinel-s2-l2a-cogs/34/S/GA/2018/6/S2A_34SGA_20180620_0_L2A/B02.tif
sentinel-cogs/sentinel-s2-l2a-cogs/35/K/KT/2018/5/S2A_35KKT_20180523_0_L2A/B02.tif

Corrupted  tif (IReadBlock failed):
sentinel-cogs/sentinel-s2-l2a-cogs/34/M/FT/2018/2/S2A_34MFT_20180228_0_L2A/B02.tif
sentinel-cogs/sentinel-s2-l2a-cogs/35/J/RN/2018/4/S2A_35JRN_20180404_0_L2A/B08.tif
```

Please let us know if this can be fixed.

**Comment by giorgiobasile** [comment]
Hi, I also report missing all scenes in [S2B_36LUM_20180701_0_L2A](https://earth-search.aws.element84.com/v0/collections/sentinel-s2-l2a-cogs/items/)

**Comment by caina-gaivota** [comment]
Hi all, I also report missing scenes for Sentinel 2 collections l1c and l2a in v1 api, and from sentinel-2-cogs from v0 api, tile ids are 22KGD and 22KGE.

**Comment by TaiWilkin** [comment]
Can you confirm if this is still an issue for you in v1? In v1, `sentinel-s2-l2a-cogs` has been renamed to `sentinel-2-l2a`.

**Comment by fungjj92** [comment]
I ran through these scenes and bands. In order as reported:

@NikitaGandhi

These scenes are available in v1:
https://earth-search.aws.element84.com/v1/collections/sentinel-2-l2a/items/S2A_31PBS_20180112_0_L2A/

In v1, the specified B02 bands are available as jp2 but missing as tifs. E.g. in `S2A_33PWM_20180124_0_L2A` we list `s3://sentinel-s2-l2a/tiles/33/P/WM/2018/1/24/0/B02.jp2` 

I successfully downloaded and opened the reported corrupted tifs from v1

@giorgiobasile

These scenes are missing in v1 and we will look into it
https://earth-search.aws.element84.com/v1/collections/sentinel-2-l2a/items/S2B_36LUM_20180701_0_L2A/

**Comment by fungjj92** [comment]
This work is captured in our JIRA
