### ISSUE TITLE
Landsat Collection - Missing Items

### ISSUE THREAD

**Issue by julianblue** [cirrus-geo/cirrus-earth-search#23]
When comparing the Landsat Archive from microsoft planetary computer and earth-search it seems like a lot of items are missing. 
Earth Search Return:
![Screenshot 2021-12-29 at 08 23 31](https://user-images.githubusercontent.com/21318315/147658885-1c945d6d-e897-4998-ab8e-65d50820234b.png)

Microsoft PC:
![Screenshot 2021-12-29 at 08 23 08](https://user-images.githubusercontent.com/21318315/147658862-dffe776b-4398-4d78-96b1-b58a212f8980.png)

Is this expected ?

**Comment by matthewhanson** [comment]
Hello Julian, the landsat collection at Earth-search is incomplete, and it's also Collection 1 do is deprecated now.

For Landsat data, use the official USGS Landsat STAC API now, which can be considered the source of truth for Landsat:
https://landsatlook.usgs.gov/stac-server
