### ISSUE TITLE
`eo:bands` Discrepancy between STAC-reported and ESA metadata for S2

### ISSUE THREAD

**Issue by tnigon** [cirrus-geo/cirrus-earth-search#24]
Reposting from [stac-server](https://github.com/stac-utils/stac-server/issues/129).

I noticed that the STAC-reported `eo:bands` values are inconsistent with what the [European Space Agency publishes in their technical guide](https://sentinel.esa.int/web/sentinel/technical-guides/sentinel-2-msi/msi-instrument).

Here is a cleaned up version of what I get from the STAC for an example scene from June 2021 ("S2A_14TQN_20210608_0_L2A"):
```
OrderedDict([('B01', {'name': 'B01', 'center': 443.9, 'fwhm': 27.0}),
             ('B02', {'name': 'B02', 'center': 496.6, 'fwhm': 98.0}),
             ('B03', {'name': 'B03', 'center': 560.0, 'fwhm': 45.0}),
             ('B04', {'name': 'B04', 'center': 664.5, 'fwhm': 38.0}),
             ('B05', {'name': 'B05', 'center': 703.9, 'fwhm': 19.0}),
             ('B06', {'name': 'B06', 'center': 740.2, 'fwhm': 18.0}),
             ('B07', {'name': 'B07', 'center': 782.5, 'fwhm': 28.0}),
             ('B08', {'name': 'B08', 'center': 835.1, 'fwhm': 145.0}),
             ('B09', {'name': 'B09', 'center': 945.0, 'fwhm': 26.0}),
             ('B11', {'name': 'B11', 'center': 1613.7, 'fwhm': 143.0}),
             ('B12', {'name': 'B12', 'center': 2220.2, 'fwhm': 242.0}),
             ('B8A', {'name': 'B8A', 'center': 864.8, 'fwhm': 33.0}),
             ('overview', {'name': 'overview', 'center': 664.5, 'fwhm': 38.0}),
             ('visual', {'name': 'visual', 'center': 664.5, 'fwhm': 38.0})])
```
The issue is that the center wavelength and FWHM exposed by the Sentinel2 STAC image is different than what is [published by the ESA](https://sentinel.esa.int/web/sentinel/technical-guides/sentinel-2-msi/msi-instrument). Many of the bands are close, but why the discrepancy?
![ESA S2 specs](https://user-images.githubusercontent.com/8249296/152615312-4d842511-7075-4361-b47a-2a6e3116d587.png)

**Comment by tnigon** [comment]
Thanks for the response at [stac-server](https://github.com/stac-utils/stac-server/issues/129) @matthewhanson. Based on your response, it sounds like the STAC metadata is more likely to be inaccurate than what is published by the ESA - is this the correct assumption?

I thought that maybe the specs may have changed at some point in time, but this seems highly unlikely. Any thoughts/insight is appreciated. Thanks again!

**Comment by matthewhanson** [comment]
@tnigon Yes, ESA would be the authoritative source on this so what they published should be used.   
I don't recall having accurate band info when I originally created those, so this is great thanks. We'll use these when we update the metadata.

**Comment by TaiWilkin** [comment]
This has been corrected in v1.
