### ISSUE TITLE
Missing Sentinel 2 L1C data - 2021-10-01 onwards

### ISSUE THREAD

**Issue by julianblue** [cirrus-geo/cirrus-earth-search#27]
Hi, 

I am seeing that the api is not returning data for L1C data towards the end of 2021 till today. What is the cause of this ?
@matthewhanson  thanks in advance.

**Comment by matthewhanson** [comment]
Hi @julianblue We were indexing the L1C data as a matter of convenience to fetch cloud cover values which were improperly set to 0 in the L2 metadata.  That problem no longer exists so I think that there is a check that no longer applies, but I'm not entirely sure as it hasn't been a big priority for us.

However, in the coming months there should be a /v1 of the API that will have a reindexed updated version of the L1C data.

**Comment by kodemi** [comment]
Hi, 
@matthewhanson have you any updates about availability of new L1C data?
