### ISSUE TITLE
missing products when search box crosses the antimeridian

### ISSUE THREAD

**Issue by ungarj** [cirrus-geo/cirrus-earth-search#29]
Following up on the discussion with @matthewhanson, there seem to be almost no products available whose footprints cross the antimeridian.

However, there is a handful of products available over Fiji for the time range of January 1st 2018 until September 1st 2022.

I did some tests to figure out how the search endpoint behaves when receiving such edge bounding boxes:

```
Fiji, on the Western side of the Antimeridian:
7 products found for bounds ['179.99', '-16.85', '180.0', '-16.83']:
S2A_1KAB_20200717_0_L2A
S2A_1KAB_20200707_0_L2A
S2A_1KAB_20200627_0_L2A
S2B_1KAB_20200622_0_L2A
S2A_1KAB_20200617_0_L2A
S2B_1KAB_20200612_0_L2A
S2B_1KAB_20200602_0_L2A

# Fiji, on the Eastern side of the Antimeridian:
7 products found for bounds ['-180', '-16.85', '-179.99', '-16.83']:
S2A_1KAB_20200717_0_L2A
S2A_1KAB_20200707_0_L2A
S2A_1KAB_20200627_0_L2A
S2B_1KAB_20200622_0_L2A
S2A_1KAB_20200617_0_L2A
S2B_1KAB_20200612_0_L2A
S2B_1KAB_20200602_0_L2A

# Fiji, on the Western side of and exceeding the Antimeridian:
7 products found for bounds ['179.99', '-16.85', '180.01', '-16.83']:
S2A_1KAB_20200717_0_L2A
S2A_1KAB_20200707_0_L2A
S2A_1KAB_20200627_0_L2A
S2B_1KAB_20200622_0_L2A
S2A_1KAB_20200617_0_L2A
S2B_1KAB_20200612_0_L2A
S2B_1KAB_20200602_0_L2A

# Fiji, on the Eastern side of and exceeding the Antimeridian:
7 products found for bounds ['-180.01', '-16.85', '-179.99', '-16.83']:
S2A_1KAB_20200717_0_L2A
S2A_1KAB_20200707_0_L2A
S2A_1KAB_20200627_0_L2A
S2B_1KAB_20200622_0_L2A
S2A_1KAB_20200617_0_L2A
S2B_1KAB_20200612_0_L2A
S2B_1KAB_20200602_0_L2A
```

The footprint of product S2A_1KAB_20200717_0_L2A does in fact cross the antimeridian:
```
POLYGON ((-179.7295810715061 -17.25484098711382, -179.7154705286898 -16.26342010381001, 179.2586344898361 -16.24777211060793, 179.2392193953623 -17.23818286390584, -179.7295810715061 -17.25484098711382))
```

So, this tells me that the search endpoint in principal works as it is able to discover these "edge" products even when the search bounds exceed the projection bounds (one has to "wrap" their head around this). However, there are only products available from June to July 2020.

Nevertheless, thanks for maintaining both archive and search endpoint!

**Comment by fungjj92** [comment]
We generally tried not to index antimeridian crossing scenes in v0. There are currently no antimeridian crossing scenes in v1 but we hope to add them in the future.
