### ISSUE TITLE
Deleted scenes - No notifications

### ISSUE THREAD

**Issue by alexgleith** [cirrus-geo/cirrus-earth-search#3]
This scene was indexed into our database: `https://sentinel-cogs.s3.us-west-2.amazonaws.com/sentinel-s2-l2a-cogs/36/J/VR/2018/1/S2B_36JVR_20180106_1_L2A/`

It does not exist now, and we didn't know about it. We should work out a way to communicate scene deletion.

**Comment by matthewhanson** [comment]
@alexgleith I'm not sure what has happened here, the item is indexed in the STAC API:
https://earth-search.aws.element84.com/v0/collections/sentinel-s2-l2a-cogs/items/S2B_36JVR_20180106_1_L2A

but none of the files are there.

I'm going to create an auditing script to get list of all items that are in the index but not on s3, and also any scenes on s3 that aren't indexed for some reason.

**Comment by TaiWilkin** [comment]
Closing this issue because these specific missing scenes are in v0. We've created a separate investigatory issue for v1 elsewhere.
