### ISSUE TITLE
Potentially broken URL

### ISSUE THREAD

**Issue by v3nkyc0d3z** [cirrus-geo/cirrus-earth-search#31]
I was trying to query the product "S2A_14SKD_20200729_0_L2A" `odc.stac.load()` and it ended up with the following error

`CPLE_OpenFailedError: '/vsicurl/https://sentinel-cogs.s3.us-west-2.amazonaws.com/sentinel-s2-l2a-cogs/14S/KD2020/7/S2A_14SKD_20200729_0_L2A/B02.tif' not recognized as a supported file format.
`

I queried for all the bands and ended up with the same error.

**Comment by omad** [comment]
Where are you running the query against?

That file doesn't exist.

```
✗ curl -I https://sentinel-cogs.s3.us-west-2.amazonaws.com/sentinel-s2-l2a-cogs/14S/KD2020/7/S2A_14SKD_20200729_0_L2A/B02.tif
HTTP/1.1 404 Not Found
x-amz-request-id: F059AZ8JJGT6AP9G
x-amz-id-2: XJxm0dkQKVUpRGiV5OHUw7bJl9I0mAV0gmDS7r9HAdVGSDRNSQ4cX2Qr7DXx6jcNN4hgWIaFIS4=
Content-Type: application/xml
Date: Sun, 06 Nov 2022 22:56:24 GMT
Server: AmazonS3
```

Using the `aws` CLI, I can't find that data either, the file naming structure is even different:

```
➜ aws s3 ls s3://sentinel-cogs/sentinel-s2-l2a-cogs/14/S/KD/2020/7/
                           PRE S2A_14SKD_20200706_0_L2A/
                           PRE S2A_14SKD_20200709_0_L2A/
                           PRE S2A_14SKD_20200716_0_L2A/
                           PRE S2A_14SKD_20200719_0_L2A/
                           PRE S2A_14SKD_20200726_0_L2A/
                           PRE S2B_14SKD_20200701_0_L2A/
                           PRE S2B_14SKD_20200704_0_L2A/
                           PRE S2B_14SKD_20200711_0_L2A/
                           PRE S2B_14SKD_20200714_0_L2A/
                           PRE S2B_14SKD_20200721_0_L2A/
                           PRE S2B_14SKD_20200724_0_L2A/
                           PRE S2B_14SKD_20200731_0_L2A/
```

**Comment by JonDHo** [comment]
This exact issue has been reported previously and I have found it across all of western Latin America for the month of August 2020 (a little bit in July). See issue https://github.com/cirrus-geo/cirrus-earth-search/issues/19

All incorrect STAC records have the same problem in the URL (the two missing "/"). Some have valid values files on S3 at the correct address, others do not.

These are the broken scenes that I have found:
![image](https://user-images.githubusercontent.com/3302774/204934987-d12642ec-9740-4639-a726-1917bc32dc4f.png)
<img width="600" alt="image" src="https://user-images.githubusercontent.com/3302774/204936595-e8816d63-5a4a-41a4-8bfa-c6b8f45bbb59.png">


I won't copy the full table here, but I have identified around 1500 scenes like this, e.g

|                             lable                            | datetime             | B01_path _BAD                                                                         |
|:------------------------------------------------------------:|----------------------|---------------------------------------------------------------------------------------|
| S2A_MSIL2A_20200816T152651_N0214_R025_T18PZU_20200816T193828 | 2020-08-16T15:29:44Z | s3://sentinel-cogs/sentinel-s2-l2a-cogs/18P/ZU2020/8/S2A_18PZU_20200816_0_L2A/B01.tif |
| S2A_MSIL2A_20200816T152651_N0214_R025_T18PXR_20200816T193828 | 2020-08-16T15:30:35Z | s3://sentinel-cogs/sentinel-s2-l2a-cogs/18P/XR2020/8/S2A_18PXR_20200816_0_L2A/B01.tif |
| S2A_MSIL2A_20200816T152651_N0214_R025_T18PXS_20200816T193828 | 2020-08-16T15:30:20Z | s3://sentinel-cogs/sentinel-s2-l2a-cogs/18P/XS2020/8/S2A_18PXS_20200816_0_L2A/B01.tif |
| S2A_MSIL2A_20200816T152651_N0214_R025_T18PXT_20200816T193828 | 2020-08-16T15:30:06Z | s3://sentinel-cogs/sentinel-s2-l2a-cogs/18P/XT2020/8/S2A_18PXT_20200816_0_L2A/B01.tif |
| S2A_MSIL2A_20200816T152651_N0214_R025_T18NXP_20200816T193828 | 2020-08-16T15:31:04Z | s3://sentinel-cogs/sentinel-s2-l2a-cogs/18N/XP2020/8/S2A_18NXP_20200816_0_L2A/B01.tif |

**Comment by tonykgill** [comment]
I too have stumbled across this issue for scenes in Australia. Again, all July and August 2020. And all with two missing "/".

Here are a few scenes. The URLs are those returned from the stac query. I can supply a complete list.

```
S2A_54KVE_20200802_0_L2A https://sentinel-cogs.s3.us-west-2.amazonaws.com/sentinel-s2-l2a-cogs/54K/VE2020/8/S2A_54KVE_20200802_0_L2A/B02.tif.
S2B_54KVE_20200728_0_L2A https://sentinel-cogs.s3.us-west-2.amazonaws.com/sentinel-s2-l2a-cogs/54K/VE2020/7/S2B_54KVE_20200728_0_L2A/B02.tif.
S2B_54KWD_20200728_0_L2A https://sentinel-cogs.s3.us-west-2.amazonaws.com/sentinel-s2-l2a-cogs/54K/WD2020/7/S2B_54KWD_20200728_0_L2A/B02.tif.
```

**Comment by TaiWilkin** [comment]
Closing this issue in favor of #19
