### ISSUE TITLE
Earth Search v1 missing scene S2A_33TXE_20221228_0_L2A

### ISSUE THREAD

**Issue by aleny91** [cirrus-geo/cirrus-earth-search#32]
Hi! First of all, I'd like to thank you for the outstanding work!
I've just noticed that the /v1 (https://earth-search.aws.element84.com/v1) of the API has been released. The structure of the items has changed with respect to the previous version. At the moment, I see that a few products still have "old" metadata (checking the JSON metadata hosted directly in the sentinel-s2-l2a-cogs bucket), therefore they are not registered in the v1.

Here is an example:

https://earth-search.aws.element84.com/v0/collections/sentinel-s2-l2a-cogs/items/S2A_33TXE_20221228_0_L2A
https://earth-search.aws.element84.com/v1/collections/sentinel-2-l2a/items/S2A_33TXE_20221228_0_L2A

When /v1 will be stable?

Many thanks in advance

**Comment by philvarner** [comment]
v1 is considered stable now.

You are correct, that scene is not in v1, but I do not know why. We'll put it on our list to look into.

**Comment by philvarner** [comment]
Scene [S2A_33TXE_20221228_0_L2A](https://earth-search.aws.element84.com/v1/collections/sentinel-2-l2a/items/S2A_33TXE_20221228_0_L2A) is not in v1, even though it should be. The curl query below should also find it by grid:code if the ID were different, but it does not.

```
curl "https://earth-search.aws.element84.com/v1/search?collections=sentinel-2-l2a&datetime=2022-12-28T00%3A59%3A27Z%2F2022-12-29T00%3A59%3A27Z&query=%7B%22grid%3Acode%22%3A%20%7B%22eq%22%3A%20%22MGRS-33TXE%22%7D%7D"
```

**Comment by fungjj92** [comment]
This work is captured in JIRA. Closing for good housekeeping.
