### ISSUE TITLE
Mislabeled collection-id starting around 2023-04-24

### ISSUE THREAD

**Issue by piyushrpt** [cirrus-geo/cirrus-earth-search#36]
We are seeing a number of items (possibly many hundreds to a couple of thousand), for which SNS Notifications were issued, that are not locatable using the STAC catalog. Here is an example set (not complete):

```
S2B_12VVR_20230424_0_L2A
S2B_10TEK_20230424_0_L2A
S2B_22XEQ_20230424_2_L2A
```

We have checked both the `v0` and `v1` endpoints.

**Comment by philvarner** [comment]
I see the first one in your list here: https://earth-search.aws.element84.com/v1/search?ids=S2B_12VVR_20230424_0_L2A
created at `2023-04-25T02:04:25.491Z`

**Comment by piyushrpt** [comment]
With `v0`
```
In [4]: URL = "https://earth-search.aws.element84.com/v0"

In [5]: query = Search(url=URL, collections=["sentinel-s2-l2a-cogs"], ids=
   ...: ["S2B_12VVR_20230424_2_L2A"])

In [6]: items = query.items()

In [7]: len(items)
Out[7]: 0
```

With `v1`
```
In [4]: URL = "https://earth-search.aws.element84.com/v1"

In [5]: query = Search(url=URL, collections=["sentinel-2-l2a"], ids=
   ...: ["S2B_12VVR_20230424_2_L2A"], limit=5)

In [6]: items = query.items()

In [7]: len(items)
Out[7]: 0
```

**Comment by philvarner** [comment]
`S2B_12VVR_20230424_2_L2A` (with _2_ rather than _0_) is not on the original list, and does not exist `s3://sentinel-s2-l2a/tiles/12/V/VR/2023/4/24/2/`

**Comment by matthewhanson** [comment]
@piyushrpt In this query,
```
query = Search(url=URL,  ids=["S2B_24XVN_20230424_2_L2A"], limit=5)
```

Check how many items are returned because the same ID should be in both the `sentinel-s2-l2a` and `sentinel-s2-l2a-cogs` collections. 

In this case, both these exist:
https://earth-search.aws.element84.com/v0/collections/sentinel-s2-l2a/S2B_24XVN_20230424_2_L2A
https://earth-search.aws.element84.com/v0/collections/sentinel-s2-l2a-cogs/S2B_24XVN_20230424_2_L2A

It does appear to be missing in the `v1` endpoint and we are working to reconcile that.

**Comment by piyushrpt** [comment]
Just a single item in `sentinel-s2-l2a` collection is returned. None in the cogs collection.

**Comment by philvarner** [comment]
> In this case, both these exist: https://earth-search.aws.element84.com/v0/collections/sentinel-s2-l2a/S2B_24XVN_20230424_2_L2A https://earth-search.aws.element84.com/v0/collections/sentinel-s2-l2a-cogs/S2B_24XVN_20230424_2_L2A

@matthewhanson  These should be `collections/sentinel-s2-l2a-cogs/items/S2B_24XVN_20230424_2_L2A` (with `items` between the collection and id), and it does look the cogs one is missing.

**Comment by matthewhanson** [comment]
Ah, whoops, thanks for checking that @philvarner.  

This one was processed and the data exists, 
https://sentinel-cogs.s3.us-west-2.amazonaws.com/sentinel-s2-l2a-cogs/24/X/VN/2023/4/S2B_24XVN_20230424_2_L2A/S2B_24XVN_20230424_2_L2A.json

Not sure why it doesn't exist in the API

**Comment by piyushrpt** [comment]
Just wanted to follow up on this. Is there a plan to update the metadata for consistency and an ETA for this update?
Or is the other collection ready for us to switch over to and use going forward?

**Comment by philvarner** [comment]
We do not have an ETA at this time.

**Comment by piyushrpt** [comment]
If it helps, we are seeing 20% of notifications to be accurate and with corresponding entries in `sentinel-s2-l2a-cogs` collection and about 80% with the `cogs` missing in the collection name over the last 3 days.

**Comment by gadomski** [comment]
This should be fixed by the [ongoing reprocessing](https://us13.campaign-archive.com/?u=a7a7fcb1ce46c4d001fc76289&id=cf7934577f). Please re-open if the issue persists after reprocessing is complete, likely in January 2024.
