### ISSUE TITLE
Support / end of life schedule for v0 vs v1

### ISSUE THREAD

**Issue by gc-sommer** [cirrus-geo/cirrus-earth-search#37]
> v0 is no longer supported, v1 data has the `boa_offset_applied` flag, see: https://earth-search.aws.element84.com/v1/collections/sentinel-2-l2a/items/S2A_32TQM_20220204_0_L2A . We would have expected to apply the offset to all v1 Sentinel 2 data where the `processing_baseline=4.00`, but the `boa_offset_applied` flag is false in that link above and for a fair amount of the metadata. We will look into it.

Hi @fungjj92 !

Could you please explain what "v0 is no longer supported" actually means? 
- is there a end of lifetime for the currently running service? Maybe I missed an announcement?
- is still data being updated in the STAC for v0 as new S2 scenes are ingested into the AWS Bucket?
- maybe this "just" means, that the STAC v0 is no longer technically updated anymore but still has current S2 data?

Best regards,
Johannes

**Comment by gadomski** [comment]
> is there a end of lifetime for the currently running service? Maybe I missed an announcement?

Currently, there is no schedule. The announcement is here: https://www.element84.com/geospatial/introducing-earth-search-v1-new-datasets-now-available/. I've also opened a PR to add a link to the announcement to the README: https://github.com/Element84/earth-search/pull/16.

An announcement will go out to [the mailing list](https://github.com/Element84/earth-search/discussions/13) in advance of the deletion of the v0 endpoint, so subscribe to that list (using [this link](https://element84.us13.list-manage.com/subscribe?u=a7a7fcb1ce46c4d001fc76289&id=38266ef009)) to ensure that you get the message.

> is still data being updated in the STAC for v0 as new S2 scenes are ingested into the AWS Bucket?

No, the v1 endpoint should be used for any new scenes. The latest STAC item in v0 appears to be from May:

```shell
$ stac-client search https://earth-search.aws.element84.com/v0 \
    -c sentinel-s2-l2a \
    --sortby='-properties.datetime' \
    --max-items 1 \
    --add-conforms-to ITEM_SEARCH \
    --add-conforms-to SORT \
    --ignore no-conforms-to | \
    jq '.features[0].properties.datetime'
"2023-05-06T16:34:15Z"
```

Closing as answered, let re-open if any of this information is unclear!
