### ISSUE TITLE
Duplicate datasets in Sentinel-2 data

### ISSUE THREAD

**Issue by tebadi** [cirrus-geo/cirrus-earth-search#4]
We observed duplicate datasets in 2019 - about 21 duplicates out of 843 datasets for one of the tiles that we looked at in 2019.

Example:

s3://sentinel-cogs/sentinel-s2-l2a-cogs/2019/S2A_30SUF_20190208_0_L2A
s3://sentinel-cogs/sentinel-s2-l2a-cogs/2019/S2A_30SUF_20190208_1_L2A

The STAC files are identical apart from the id but .tif files are of different sizes.

The question is what causes these duplicates, and which one is valid e.g latest?

**Comment by matthewhanson** [comment]
@tebadi The sequence numbers are different here, "_1_L2A.json" vs "_0_L2A.json".  See documentation here:
https://roda.sentinel-hub.com/sentinel-s2-l2a/readme.html

The sequence number is indicated to be the image number within a single day.  In most cases this is just one, but sometimes there can be more than one.   I've seen this before though where the images look the same, and not entirely sure what the difference is or how sequence number is intended here.

Also, from earlier conversation with Sinergise it sounded like they might be using sequence number to indicate a reprocessed scene, which sounds more like a version identifier.

Sounds like we need to get to the bottom of how and why sequence numbers would change. If these are basically versions then it needs to be handled differently.

**Comment by Kirill888** [comment]
For these two at least, `sentinel:product_id` suggests reprocessing on different days

```
S2A_MSIL2A_20190208T110221_N0211_R094_T30SUF_20190208T134432
S2A_MSIL2A_20190208T110221_N0211_R094_T30SUF_20190214T163527
```

**Comment by Kirill888** [comment]
SCL looks cleaner on a `_1` (right) vs  `_0` (left), way less of junk bare earth classifications in the middle of the clouds, sorry about zoom mismatch

![image](https://user-images.githubusercontent.com/1428024/97379679-6d168000-1919-11eb-977a-c2eddcf63d8a.png)

**Comment by fungjj92** [comment]
Version identifier number indicates multiple satellite images taken on the same day, not a duplicate. Closing.

**Comment by fungjj92** [comment]
Sometimes more than one scene is taken in a given day.  Some times, at northern latitudes, these are actually different scenes.  But sometimes they are just reprocessed scenes.  Ideally we need a way to differentiate those and be able to remove older ones that have been reprocessed. Supposedly ESA publishes IDs of old scenes that can be replaced. In this case we want to remove the old scenes, however using the sequence number alone we actually don't know if it's a separate scene taking on the same day, or a reprocessed scene. 

We have moved this issue into our JIRA ticket tracking system to solve, and will close this issue for good housekeeping. Thanks for bringing this up!
