### ISSUE TITLE
Invalid geometry detected in two datasets

### ISSUE THREAD

**Issue by tebadi** [cirrus-geo/cirrus-earth-search#5]
We've detected the following files to have invalid geometry:

s3://sentinel-cogs/sentinel-s2-l2a-cogs/39/M/XR/2020/9/S2A_39MXR_20200909_0_L2A/S2A_39MXR_20200909_0_L2A.json: this one is essentially a line.

s3://sentinel-cogs/sentinel-s2-l2a-cogs/27/P/YR/2019/6/S2A_27PYR_20190620_0_L2A/S2A_27PYR_20190620_0_L2A.json

Please ensure datasets have valid geometry before they're generated.

**Comment by matthewhanson** [comment]
@tebadi 

Not sure what happened to S2A_39MXR_20200909_0_L2A 
https://earth-search.aws.element84.com/v0/collections/sentinel-s2-l2a-cogs/items/S2A_39MXR_20200909_0_L2A

The provided geometry is actually not of the actual image, as shown here:
![image](https://user-images.githubusercontent.com/1416900/101865958-a1e73b00-3b45-11eb-8958-6402c722acff.png)

The red line above the image is what the geometry is showing the boundaries are.

The other one appears valid to me:
https://earth-search.aws.element84.com/v0/collections/sentinel-s2-l2a-cogs/items/S2A_27PYR_20190620_0_L2A

![image](https://user-images.githubusercontent.com/1416900/101866397-b1b34f00-3b46-11eb-9644-c415449f4e0d.png)

The image is small, in the water off the coast of Dakar, but the polygon is accurate.  What did you find that was invalid about it?

**Comment by matthewhanson** [comment]
For the invalid geometry I think there are 2 things to be done.

- First, determine why the geometry doesn't match. Is the original geometry in tileInfo.json the same or was there an error in re-projecting those coordinates?
- Determine what constitutes an invalid geometry.  The first one isn't really invalid either, it's just a very slender triangle.  Should there be a minimum size of images to drop?

**Comment by fungjj92** [comment]
This work is captured in JIRA, so closing.
