### ISSUE TITLE
Partial scenes in sentinel-cogs

### ISSUE THREAD

**Issue by tebadi** [cirrus-geo/cirrus-earth-search#6]
We've detected the following scenes in sentinel-cogs to have missing bands:

https://earth-search.aws.element84.com/v0/collections/sentinel-s2-l2a-cogs/items/S2A_28QBM_20180205_0_L2A
https://earth-search.aws.element84.com/v0/collections/sentinel-s2-l2a-cogs/items/S2B_39PUK_20181223_0_L2A
https://earth-search.aws.element84.com/v0/collections/sentinel-s2-l2a-cogs/items/S2A_35KKT_20180523_0_L2A
https://earth-search.aws.element84.com/v0/collections/sentinel-s2-l2a-cogs/items/S2B_30SWD_20181013_0_L2A
https://earth-search.aws.element84.com/v0/collections/sentinel-s2-l2a-cogs/items/S2A_36NTH_20180801_0_L2A
https://earth-search.aws.element84.com/v0/collections/sentinel-s2-l2a-cogs/items/S2A_33PWM_20180124_0_L2A
https://earth-search.aws.element84.com/v0/collections/sentinel-s2-l2a-cogs/items/S2B_29SPR_20181118_0_L2A
https://earth-search.aws.element84.com/v0/collections/sentinel-s2-l2a-cogs/items/S2A_36PZB_20181126_0_L2A
https://earth-search.aws.element84.com/v0/collections/sentinel-s2-l2a-cogs/items/S2B_33PTQ_20180909_0_L2A
https://earth-search.aws.element84.com/v0/collections/sentinel-s2-l2a-cogs/items/S2B_34SCA_20181115_0_L2A
https://earth-search.aws.element84.com/v0/collections/sentinel-s2-l2a-cogs/items/S2A_32LRP_20181127_0_L2A
https://earth-search.aws.element84.com/v0/collections/sentinel-s2-l2a-cogs/items/S2A_34NHM_20180919_0_L2A
https://earth-search.aws.element84.com/v0/collections/sentinel-s2-l2a-cogs/items/S2B_35RKL_20181116_0_L2A
https://earth-search.aws.element84.com/v0/collections/sentinel-s2-l2a-cogs/items/S2B_39NUE_20180726_0_L2A
https://earth-search.aws.element84.com/v0/collections/sentinel-s2-l2a-cogs/items/S2A_39PTN_20181012_0_L2A
https://earth-search.aws.element84.com/v0/collections/sentinel-s2-l2a-cogs/items/S2A_35RLH_20180724_0_L2A
https://earth-search.aws.element84.com/v0/collections/sentinel-s2-l2a-cogs/items/S2A_34SGA_20180620_0_L2A
https://earth-search.aws.element84.com/v0/collections/sentinel-s2-l2a-cogs/items/S2A_31PBS_20180112_0_L2A
https://earth-search.aws.element84.com/v0/collections/sentinel-s2-l2a-cogs/items/S2B_35LKC_20181227_1_L2A
https://earth-search.aws.element84.com/v0/collections/sentinel-s2-l2a-cogs/items/S2B_34PDQ_20180722_0_L2A
https://earth-search.aws.element84.com/v0/collections/sentinel-s2-l2a-cogs/items/S2B_35MNM_20180905_0_L2A
https://earth-search.aws.element84.com/v0/collections/sentinel-s2-l2a-cogs/items/S2A_35MKS_20181016_0_L2A
https://earth-search.aws.element84.com/v0/collections/sentinel-s2-l2a-cogs/items/S2B_39PVL_20181223_0_L2A
https://earth-search.aws.element84.com/v0/collections/sentinel-s2-l2a-cogs/items/S2A_37LDD_20181104_0_L2A

Please let us know if this can be fixed.

**Comment by matthewhanson** [comment]
This is peculiar, because the workflow should fail if any of the conversions fail. I'll rerun these, see if it happens again and explore the logs.

**Comment by TaiWilkin** [comment]
This is fixed in v1.
